name: nerfmm
channels:
  - pytorch
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - cudatoolkit
  - torchvision
  - tqdm
  - imageio
  - pip:
    - tensorflow # only for tensorboard
    - imageio-ffmpeg
    - lpips
    - scikit-image
    - open3d
  